### ISSUE TITLE
bug: CI breaks when trying to download LuaJIT from 

### ISSUE THREAD

**Issue by mikyll** [casbin/lua-casbin#160]
## Description

CI workflows include a step which uses [**leafo/gh-actions-lua**](https://github.com/marketplace/actions/install-lua-luajit#inputs) to download LuaJIT from [LuaJIT.org](http://luajit.org/download.html):

> Anything starting with luajit- — from http://luajit.org/download.html

However, as stated on their website, LuaJIT.org doesn't serve tarballs anymore:

> There are no release tarballs available for download.

Since [build](https://github.com/casbin/lua-casbin/blob/master/.github/workflows/build.yml) workflow is using `luaVersion: "luajit"` for some CI steps, the workflow fails because LuaJIT.org responds with `404`:

![image](https://github.com/user-attachments/assets/d18443cb-8697-475f-9b8d-5b6c237db846)

Related issue: https://github.com/leafo/gh-actions-lua/issues/49

## Possible Fix

**Change LuaJIT repository**, for example to OpenResty: [luajit-openresty](https://github.com/openresty/luajit2)

File `.github/workflows/build.yml`:

```yaml
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Here change from "luajit" to "luajit-openresty"
        lua-version: ["5.1", "5.2", "5.3", "5.4", "luajit-openresty"]
```
